server:
  port: 8093

spring:
  application:
    name: msvc-lines
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.0.20:1433;databaseName=reportes;encrypt=true;trustServerCertificate=true;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServerDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka