server:
  port: 8094

spring:
  application:
    name: msvc-branches
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.0.20:1433;databaseName=sucursales;encrypt=true;trustServerCertificate=true;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServerDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka